---
title: "Curso Biodata"
description: |
  Gestión de bases de datos de biodiversidad
site: 
  distill::distill_website:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```



Este sitio web presenta el material para el curso presencial intensivo *Biodata: Gestión de bases de datos de biodiversidad*, organisado por el Instituto de Ecología & Biodiversidad del 13 al 17 de noviembre de 2023, en la Facultad de Ciencias Naturales y Oceanograficas de la Universidad de Concepción (UdeC).


# Programa

En esta semana, los temas que vamos a trabajar se pueden dividir así: 

1. Presentación introductiva: pensar la gestión de los datos de biodiversidad en el entorno cientifico y social actual
1. Manejar datos en R: entender como filtrar, seleccionar, manejar datos en R
1. Manejar datos en SQL: consultas simples y avanzadas en SQL, pensar la estructura de una base de datos, modificar y manejar una base de datos SQL
1. Expresiones regulares en R y SQL: manejar las cadenas de carácter en las bases de datos 
1. Estructura de la biodiversidad, estructura de los proyectos de investigación y monitoreo, estructura de los datos: ¿como pensarlos juntos?
1. Taxonomía: manejar datos taxonómicos en R y SQL
1. Datos espaciales: manejar datos espaciales en Qgis, R, y SQL
1. El nuevo modelo de los datos de biodiversidad de Chile (presentación por [Julián Cabezas Peña](https://www.juliancabezas.com/))
1. Herramientas de hacker para los datos de biodiversidad: Github, paquetes R etc.
1. Proyecto final: un ejemplo aplicado de gestión de los datos

El plan de tiempo que tenemos es:

| Día | Mañana | Tarde |
|-----|---------|------------|
| Lunes | Presentación introductiva, empezar las actividades de R | Actividades en R |
| Martes | SQL, expresiones regulares | SQL, estructuras de la biodiversidad/proyectos/datos |
| Miercoles | Taxonomía | Datos espaciales |
| Jueves | Modelo de datos de biodiversidad en Chile | Modelo de datos de biodiversidad en Chile |
| Viernes | Herramientas de hackers | Proyecto final |



# Instalación de los software y paquetes

En el curso, vamos a utilizar lo más posible software libre.
En las paginas siguientes pueden encontrar los enlaces y instrucciones para instalar los software:

* [Windows](./inst_software_windows.html)
* [Linux](./inst_software_linux.html)
* [Mac OS](./inst-software_macOS.html)

[Instalar los paquetes R](./inst_paquetes_R.html) (Cuidado, este documento no está terminado, por favor volver a mirarlo 1-2 días antes del curso)


# Presentaciones

* [Presentación introductoria del curso](https://docs.google.com/presentation/d/1l-kktBV9cM-4mRmelO9Q10KaTazcKD3NpXsdHmhPIIQ/edit?usp=sharing)


# Actividades


# Datos

Los datos necesarios para los ejercicios y actividades están disponibles en [Google drive](https://drive.google.com/drive/folders/1hnp4NwjEXu4uNVZYKagMY5CNkEX6XNg2?usp=drive_link). Para poder acceder, por favor llenar este [formulario](https://docs.google.com/forms/d/e/1FAIpQLScM2bj_UTcHs4sEzfuQDJAdn-Kxs5vUYs7Y97fLiZBHxps5mA/viewform?usp=sf_link).

# Documentación

# Soluciones de los ejercicios

Si quieren que los ejercicios sean útiles para desarrollar sus capacidades de programación en R y SQL, es mejor enfrentarse a las dificultades y buscar soluciones por sí mismo.
Sin embargo, es muy probable que no tengamos el tiempo para resolver todos los ejercicios, acá encontrarán las soluciones que propongo yo.
Anotar: en programación, existen varios caminos para obtener el mismo resultado, no descarten su propia solución por no ser igual a la solución que proponga...

* [Solución de la actividad manejar datos en R](act_R_intro_corr.html)
